sudo: required

language: python
python:
  - "2.7"
services:
  - docker
  
env:
  - TEST_SUITE="quality"
  - TEST_SUITE="lms-unit"
    SHARD=1
  - TEST_SUITE="lms-unit"
    SHARD=2
  - TEST_SUITE="lms-unit"
    SHARD=3
  - TEST_SUITE="lms-unit"
    SHARD=4
  - TEST_SUITE="cms-unit"
  - TEST_SUITE="commonlib-unit"
  - TEST_SUITE="js-unit"
  - TEST_SUITE="lms-acceptance"
  - TEST_SUITE="cms-acceptance"
  - TEST_SUITE="bok-choy"
    SHARD=1
  - TEST_SUITE="bok-choy"
    SHARD=2
  - TEST_SUITE="bok-choy"
    SHARD=3
  - TEST_SUITE="bok-choy"
    SHARD=4
  - TEST_SUITE="bok-choy"
    SHARD=5
  - TEST_SUITE="bok-choy"
    SHARD=6
  - TEST_SUITE="bok-choy"
    SHARD=7
  - TEST_SUITE="bok-choy"
    SHARD=8
  - TEST_SUITE="bok-choy"
    SHARD=9
  - TEST_SUITE="bok-choy"
    SHARD=10
  - TEST_SUITE="bok-choy"
    SHARD=11

branches:
  only:
  - master
  - oxa/master.fic
  - oxa/dev.fic
  - oxa/dev.fic-hotfix
  - oxa/dev.fic-quality
  - oxa/ci
  - oxa/ci-docker
  - oxa/ci-docker-qual

before_install:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker pull btelnes/devstack

install:
  - docker run -d --name devstack --security-opt seccomp=unconfined --tmpfs /run --tmpfs /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro -e TEST_SUITE="$TEST_SUITE" -e SHARD="$SHARD" -e CODE_COV_TOKEN="$CODE_COV_TOKEN" -t btelnes/devstack
  - docker --version  
  - docker ps -a
  
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  
script: 
  - ./scripts/docker-run-tests.sh

after_success:
  - ./scripts/docker-report.sh

addons:
  firefox: "45.0"
  chrome: stable

dist: trusty
